# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      # Runs a single command using the runners shell
      - name: Create build dir
        run: mkdir build

      - name: Create dist dir
        run: mkdir dist

      - name: Copy eledio-app
        run: cp eledio-app build/eledio-app

      - name: Copy app
        run: cp -r app build/app

      - name: Set chmod
        run: chmod a+x build/eledio-app

      - name: Get and set version
        run: |
          VERSION=$("tools/long-version")
          echo $VERSION
          python3 tools/replace "build/eledio-app" '{{$APPVERSION$}}' "$VERSION"

      - name: Create dist
        run: tar -cvf "dist/eledio-app.tar" --owner=0 --group=0 -C "build" .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eledio-app
          path: dist/eledio-app.tar
